import { makeStyles } from "@material-ui/styles"
import { Theme } from "@material-ui/core/styles/createMuiTheme"

const useStyles = makeStyles((theme: Theme) => ({
  container: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#fafafa",
    padding: "15px 10px 5px 10px",
    borderBottom: "1px solid #eeeeee",
    position: "relative",
  },
  contentHeader: {
    fontFamily: "Lato",
    fontSize: "11px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#afafaf",
    marginBottom: "3px",
  },
  carrierInfo: {
    display: "flex",
    flexDirection: "row",
    marginTop: "3px",
    marginBottom: "10px",
    alignItems: "flex-end",
  },
  userName: {
    fontFamily: "Lato",
    fontSize: "14px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#2dd75c",
  },
  isTrusted: {
    marginLeft: "3px",
    marginBottom: "3px",
    color: "#54c652",
    fontSize: "10px",
    border: "1px solid #2dd75c",
    borderRadius: "5px",
  },
  reviews: {
    margin: "1px 0px 1px 5px",
    fontFamily: "Lato",
    fontSize: "10px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#9773ff",
  },
  transferPeople: {
    position: "absolute",
    top: 15,
    right: 10,
    fontFamily: "Roboto",
    fontSize: "10px",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#fc6666",
  },
  tags: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  tag: {
    marginRight: "8px",
    marginTop: "5px",
    padding: "2px 4px 2px 4px",
    height: "20px",
    borderRadius: "4px",
    border: "solid 1px #f6e338",
    fontFamily: "Lato",
    fontSize: "12px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "italic",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#8d8d8d",
  },
  displayAllWrapper: {
    marginTop: "10px",
    alignSelf: "center",
    width: "20px",
    height: "20px",
  },
  controlArrow: {},
}))

export default useStyles
