import { makeStyles } from "@material-ui/styles"
import { Theme } from "@material-ui/core/styles/createMuiTheme"

const useStyles = makeStyles((theme: Theme) => ({
  container: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    paddingTop: "10px",
  },
  transferNumber: {
    display: "flex",
    flexDirection: "row",
  },
  title: {
    display: "flex",
    flexDirection: "column",
    minHeight: "45px",
    borderBottom: "1px solid #eeeeee",
    padding: "0 10px",
  },
  premiumStar: {
    margin: "2px 0 0 0",
    color: "#f5f92a",
  },
  premiumFont: {
    color: "#fed133",
  },
  transferNumberText: {
    margin: "4px 0 3px 0",
    fontFamily: "Lato",
    fontSize: "16px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#54c652",
  },
  mainContent: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#fafafa",
    padding: "15px 10px",
    borderBottom: "1px solid #eeeeee",
  },
  departureInfo: {
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    textAlign: "left",
    maxWidth: "40%",
    display: "flex",
    flexDirection: "column",
  },
  deliveryInfo: {
    overflow: "hidden",
    whiteSpace: "nowrap",
    direction: "rtl",
    textAlign: "right",
    maxWidth: "40%",
    display: "flex",
    flexDirection: "column",
  },
  contentText: {
    marginBottom: "8px",
    fontFamily: "Lato",
    fontSize: "18px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#8f8f8f",
  },
  placeText: {
    whiteSpace: "normal",
    fontFamily: "Lato",
    fontSize: "16px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#a365b9",
    marginBottom: "8px",
  },
  date: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    fontFamily: "Lato",
    fontSize: "15px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#54c652",
  },
}))

export default useStyles
