import { makeStyles } from "@material-ui/styles"
import { Theme } from "@material-ui/core/styles/createMuiTheme"

const useStyles = makeStyles((theme: Theme) => ({
  modal: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "scroll",
    scrollbarWidth: "none" /* Firefox */,
    msOverflowStyle: "none" /* IE 10+ */,
    "&::-webkit-scrollbar": {
      width: "0px",
      background: "transparent" /* Chrome/Safari/Webkit */,
    },
    padding: "30px 0 0 0",
    "@media (max-width: 1300px)": {
      alignItems: "baseline",
    },
  },
  wrapper: {
    width: "700px",
    height: "700px",
    padding: "40px",
    display: "flex",
    flexDirection: "column",
    backgroundImage: `url(${"https://res.cloudinary.com/drkgnohds/image/upload/v1589877880/SUP/Background_q9pg1z.png"})`,
    backgroundRepeat: "no-repeat",
    backgroundSize: "120% 100%",
    backgroundColor: "#ffffff",
    borderRadius: "20px",
    outline: "none",
    "@media (max-width: 800px)": {
      width: "90%",
      padding: "20px 20px",
    },
  },
  headerContent: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  supLogo: {
    fontSize: "32px",
    fontWeight: 900,
    fontStretch: "normal",
    fontStyle: "italic",
    lineHeight: "normal",
    letterSpacing: "-3px",
    color: "#78f464",
  },
  contentHeader: {
    padding: "0 0 6px 0",
    alignSelf: "end",
    fontSize: "14px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "notmal",
    color: "#3e3e3e",
  },
  closeIcon: {
    alignSelf: "end",
    width: "40px",
    height: "40px",
  },
  stepper: {
    display: "flex",
    width: "100%",
  },
  stepperWrapper: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  },
  stepperControls: {
    display: "flex",
    height: "70px",
    flexDirection: "column",
    alignContent: "flex-end",
    padding: "0 10px 0 0",
  },
  prevButton: {
    borderRadius: "4px",
    border: "solid 1px #d8eadd",
    height: "35px",
    width: "80px",
    margin: "0 10px 0 0",
  },
  nextButton: {
    borderColor: "#30bb49",
    borderRadius: "4px",
    height: "35px",
    width: "80px",
    backgroundImage: `url(${"https://res.cloudinary.com/drkgnohds/image/upload/c_fill,h_45,w_110/v1588516370/SUP/logo512_kpt9pr.png"})`,
    backgroundRepeat: "no-repeat",
    backgroundSize: "100% 100%",
  },
  nextButtonText: {
    textTransform: "none",
    fontSize: "14px",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#ffffff",
  },
  prevButtonText: {
    textTransform: "none",
    fontSize: "14px",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#333333",
  },
  createOfferForm: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    height: "100%",
    width: "100%",
  },
  inputLabel: {
    fontSize: "0.875rem",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "0.28px",
    color: "#8e8e8e",
  },
  inputField: {
    margin: "0 0 1.5rem 0",
    width: "100%",
  },
  inputWrapper: {
    display: "flex",
    flexDirection: "column",
    alignSelf: "center",
    width: "60%",
    margin: "60px 0 0 0",
    "@media (max-width: 800px)": {
      width: "85%",
    },
  },
  fieldsEmpty: {
    color: "red",
    alignSelf: "center",
    margin: "0 0 10px 0",
  },
  buttonsWrapper: {
    display: "flex",
    flexDirection: "row",
    alignSelf: "flex-end",
  },
  inputTextAreaField: {
    margin: "0.5rem 0 1.5rem 0",
    width: "100%",
    borderRadius: "4px",
    border: "1px solid #5cff89",
  },
  inputFieldNumber: {
    margin: "0.5rem 0 1.5rem 0",
    width: "100%",
    padding: "0 10px 0 0",
    "& input[type=number]": {
      "&::-webkit-inner-spin-button, &::-webkit-outer-spin-button": {
        webkitAppearance: "none",
        appearance: "none",
        margin: 0,
      },
      "-moz-appearance": "textfield",
    },
  },
  inputPriceWrapper: {
    width: "63px",
    height: "40px",
    display: "flex",
    justifyContent: "space-between",
  },
  dollar: {
    display: "flex",
    alignSelf: "flex-end",
    padding: "0 0 6px 0",
  },
  chip: {
    fontSize: "0.9rem",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#000000",
  },
  autocomplete: {
    margin: "7px 0 10px 0",
  },
  clearIndicator: {
    right: "20px",
  },
}))

export default useStyles
