import { makeStyles } from "@material-ui/styles"
import { Theme } from "@material-ui/core/styles/createMuiTheme"

const useStyles = makeStyles((theme: Theme) => ({
  wrapper: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  sugBoardsBox: {
    marginTop: "30px",
    marginLeft: "3%",
    marginBottom: "10px",
    height: "47px",
    fontFamily: "Lato",
    fontSize: "24px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "italic",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#999999",
  },
  infoMessageWrapper: {
    marginTop: "30px",
    alignSelf: "center",
  },
  infoMessage: {
    fontFamily: "Lato",
    fontSize: "15px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "italic",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#000000",
  },
  altQueryMessage: {
    fontFamily: "Lato",
    fontSize: "15px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "italic",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#2cdc00",
  },
  noticeCard: {
    minHeight: "190px",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    backgroundImage: "linear-gradient(to right, rgba(240, 240, 240, 0.92), rgba(245, 245, 245, 0))",
  },
  noticeMedia: {
    marginTop: "30px",
    marginLeft: "33px",
    width: "220px",
    height: "140px",
    borderRadius: "11px",
  },
  cardBody: {
    position: "relative",
    height: "190px",
    width: "63%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  vehicleType: {
    height: "14px",
    width: "27px",
    marginTop: "3px",
    textAlign: "center",
    border: "1px solid green",
    borderRadius: "5px",
    opacity: "0.4",
    fontSize: "9px",
    color: "green",
  },
  generalData: {
    marginTop: "15px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  vehicleInfo: {
    marginLeft: "17px",
    fontFamily: "Lato",
    fontSize: "18px",
    fontWeight: 500,
    lineHeight: "normal",
    color: "#464746",
  },
  noticeProvider: {
    marginTop: "2px",
    fontFamily: "Roboto",
    fontSize: "15px",
    lineHeight: "normal",
    fontWeight: 300,
    color: "#959595",
  },
  highlightMaxWeight: {
    margin: 0,
    width: "32px",
    height: "1px",
    backgroundColor: "#e7e7e7",
    opacity: "0.4",
  },
  isTransferPeople: {
    marginTop: "30px",
    fontFamily: "Lato",
    fontSize: "17px",
    fontWeight: 900,
    lineHeight: "normal",
    color: "#9dfb95",
  },
  isNotTransferPeople: {
    marginTop: "30px",
    fontFamily: "Lato",
    fontSize: "17px",
    fontWeight: 800,
    lineHeight: "normal",
    color: "#ff9595",
  },
  starRate: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "end",
  },
  rating: {
    height: "auto",
    width: "100px",
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    alignItems: "flex-end",
    top: "34px",
    right: 0,
  },
  starIcon: {
    fontSize: "12px",
    color: "#a788ff",
  },
  starRating: {
    marginLeft: "5px",
    fontSize: "10px",
    color: "#a788ff",
  },
  reviews: {
    fontFamily: "Lato",
    fontSize: "10px",
    fontWeight: 500,
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#a6a6a6",
  },
  estimatedPrice: {
    position: "absolute",
    bottom: "25px",
    right: 0,
    fontFamily: "Roboto",
    fontSize: "15px",
    fontWeight: 900,
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#6f6f6f",
  },
}))

export default useStyles
