import { makeStyles } from "@material-ui/styles"
import { Theme } from "@material-ui/core/styles/createMuiTheme"

const useStyles = makeStyles((theme: Theme) => ({
  dashboard: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#fafafa",
    padding: "5px",
    overflowY: "scroll",
    scrollbarWidth: "none" /* Firefox */,
    msOverflowStyle: "none" /* IE 10+ */,
    "&::-webkit-scrollbar": {
      width: "0px",
      background: "transparent" /* Chrome/Safari/Webkit */,
    },
  },
  boardNoticeWrapper: {
    padding: "5px",
    width: "100%",
    minHeight: "100px",
    backgroundColor: "#FFFFFF",
    marginBottom: "5px",
  },
  premiumStar: {
    color: "#f5f92a",
  },
  cardContent: {
    margin: 0,
    padding: "6px 0",
    width: "100%",
    height: "49%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  mainInfo: {
    display: "flex",
    flexDirection: "column",
    maxWidth: "50%",
  },
  route: {
    display: "flex",
  },
  routeText: {
    fontFamily: "Lato",
    fontSize: "15px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#464746",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  transferNumber: {
    fontFamily: "Lato",
    fontSize: "8px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#a3a3a3",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tags: {
    display: "flex",
    flexDirection: "row",
    justifySelf: "flex-start",
  },
  tag: {
    height: "16px",
    fontSize: "8px",
    padding: "2px",
    marginLeft: "10px",
    borderRadius: "4px",
    border: `1px solid black`,
  },
  reviews: {
    minWidth: "55px",
    justifySelf: "end",
    fontFamily: "Lato",
    fontSize: "10px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#9773ff",
  },
  leftSideContent: {
    overflow: "hidden",
    width: "80%",
    display: "flex",
    flexDirection: "row",
  },
  contentDivider: {
    height: "1px",
    width: "72px",
    backgroundImage: "linear-gradient(to top, #e7e7e7, rgba(255, 255, 255, 0))",
  },
  pickUpPlace: {
    display: "flex",
    flexDirection: "column",
    width: "28%",
    justifyContent: "space-between",
  },
  cardBottomContentHeader: {
    fontFamily: "Lato",
    fontSize: "6px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#afafaf",
  },
  cardBottomContent: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "Lato",
    fontSize: "10px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#2dd75c",
  },
  cardBottomDate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "Lato",
    fontSize: "8px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#838383",
  },
  isPeopleTransfer: {
    fontFamily: "Roboto",
    fontSize: "8px",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
  },
  cargoInfo: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
  },
  pricePerValue: {
    alignSelf: "end",
    fontFamily: "Roboto",
    fontSize: "10px",
    fontWeight: 900,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    color: "#6f6f6f",
  },
  carrier: {
    display: "flex",
    flexDirection: "column",
    width: "20%",
  },
  isTrusted: {
    marginTop: "2px",
    marginLeft: "2px",
    color: "#2dd75c",
    fontSize: "8px",
    border: "1px solid #2dd75c",
    borderRadius: "4px",
  },
  carrierInfo: {
    display: "flex",
    marginTop: "2px",
  },
}))

export default useStyles
